project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "tournament-announcements/dubose-open2026.qmd"
    - "!tournament-announcements/dubose-open2025.qmd"
    - "!resumes/"

website:
  title: "Kline DuBose"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: main_about.qmd
        text: About
      - href: main_projects.qmd
        text: Projects
      - href: main_presentation.qmd
        text: Presentations
  page-footer:
    background: light
    left:
      - icon: twitter-x
        href: https://x.com/KlineDuBose
      - icon: github
        href: https://github.com/KPDuBose
      - icon: linkedin
        href: https://www.linkedin.com/in/kline-dubose/
      - icon: envelope
        href: mailto:kline.dubose@utah.edu
    right:
      - "295 Chipeta Way, 3rd Floor
         Salt Lake City, UT 84108
         United States"

format:
  html:
    theme: 
      - morph
      - custom.scss
    css: styles.css
    toc: true



